root:
    path: /
    defaults:
        _controller: FrameworkBundle:Redirect:urlRedirect
        path: /es/portada
        permanent: true
    requirements:
       _locale: en|es
       
app_corredores_rioja_portada:
    path:     /{_locale}/portada
    defaults: { _controller: AppCorredoresRiojaBundle:Corredor:mostrarCarrerasFuturas }
    requirements:
       _locale: en|es
       
app_corredores:
    resource: '@AppCorredoresRiojaBundle/Resources/config/corredoresRouting.yml'
    prefix:   /{_locale}/corredores
    requirements:
       _locale: en|es