services:
#    app_corredores_rioja.example:
#        class: App\CorredoresRiojaBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
    carrerarepository:
        class: App\CorredoresRiojaInfrastructure\InMemoryRepository\InMemoryCarreraRepository

    corredorrepository:
        class: App\CorredoresRiojaInfrastructure\InMemoryRepository\InMemoryCorredorRepository

    organizacionrepository:
        class: App\CorredoresRiojaInfrastructure\InMemoryRepository\InMemoryOrganizacionRepository

    participanterepository:
        class: App\CorredoresRiojaInfrastructure\InMemoryRepository\InMemoryParticipanteRepository
